version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: dev
      MYSQL_PASSWORD: password
      MYSQL_UNIX_PORT: ""
      MYSQL_TCP_PORT: 3306
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
    command:
      - --default-authentication-plugin=mysql_native_password
    entrypoint:
      - sh
      - -c
      - >
        echo "CREATE USER 'dev'@'%' IDENTIFIED BY 'password';" | mysql -u root -proot;
        echo "GRANT ALL PRIVILEGES ON *.* TO 'dev'@'%';" | mysql -u root -proot;
        echo "CREATE DATABASE dev;" | mysql -u root -proot;
        echo "USE dev; source /var/lib/mysql/schema.sql;" | mysql -u root -proot;
        exec mysqld
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - 8091:80
    links:
      - db:db
  dev:
    build: .
      
    ports:
      - "8081:8080"
      - "2222:2222"
    volumes:
      - ${HOME}:/home/dev
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker:/var/lib/docker
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock 
