version: '3'
services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: dev
      MYSQL_PASSWORD: devpassword
      MYSQL_DATABASE: dev
    volumes:
      - mysql-data:/var/lib/mysql
    command:
      - --default-authentication-plugin=mysql_native_password
    entrypoint:
      - bash
      - -c
      - |
        set -e
        mysql -h localhost -u root -prootpassword -e "CREATE USER 'dev'@'%' IDENTIFIED BY 'devpassword'; GRANT ALL PRIVILEGES ON *.* TO 'dev'@'%' WITH GRANT OPTION; CREATE DATABASE dev;"
        mysql -h localhost -u dev -pdevpassword dev < /database-script.sql

volumes:
  mysql-data:

