version: '3'
networks:
  app-network:
    driver: bridge
services:
  app:
    build: .
    ports:
      - "3000:3000"
  db:
    image: db
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - 8091:80
    links:
      - db:db
    networks:
      - app-network
  dev:
    image: dev-docfile
    ports:
      - "8081:8080"
      - "2222:2222"
    volumes:
      - ${HOME}:/home/dev
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker:/var/lib/docker
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    networks:
      - app-network
